### ISSUE TITLE
TypeError: Object #<Object> has no method 'execSync'

### ISSUE THREAD

**Issue by coderholic** [zhanzhenzhen/js-bundler#1]
```
$ bundle -c:coffee 'coffee -bcs' app.coffee

/usr/local/lib/node_modules/js-bundler/src/main.coffee:35
(command = compileCommands[rawCodeType], command != null ? cprocess.execSync(c
                                                                    ^
TypeError: Object #<Object> has no method 'execSync'
  at checkCode (/usr/local/lib/node_modules/js-bundler/src/main.coffee:24:26)
  at Object.<anonymous> (/usr/local/lib/node_modules/js-bundler/src/main.coffee:127:1)
  at Object.<anonymous> (/usr/local/lib/node_modules/js-bundler/src/main.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/usr/local/lib/node_modules/js-bundler/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/js-bundler/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/js-bundler/bin/bundle:4:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3

$ node --version
v0.10.29
$ coffee --version
CoffeeScript version 1.7.1
```

**Comment by zhanzhenzhen** [comment]
This is a known issue. I used the synchronous `exec` method to run coffeescript compiling commands. It's easier to write than its async version, but requires Node 0.11+. I hope Joyent will release Node 0.12 soon.

**Comment by coderholic** [comment]
I'm trying with 0.11 but now getting this error:

```
$ bundle -c:coffee 'coffee -bcs' app.coffee
fs.js:443
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'stream'
  at Error (native)
  at Object.fs.openSync (fs.js:443:18)
  at Object.fs.readFileSync (fs.js:309:15)
  at checkCode (/usr/local/lib/node_modules/js-bundler/src/main.coffee:14:18)
  at checkTreeNode (/usr/local/lib/node_modules/js-bundler/src/main.coffee:50:17)
  at /usr/local/lib/node_modules/js-bundler/src/main.coffee:55:46
  at Array.forEach (native)
  at checkTreeNode (/usr/local/lib/node_modules/js-bundler/src/main.coffee:55:31)
  at /usr/local/lib/node_modules/js-bundler/src/main.coffee:53:33
  at Array.forEach (native)
  at checkTreeNode (/usr/local/lib/node_modules/js-bundler/src/main.coffee:53:18)
  at /usr/local/lib/node_modules/js-bundler/src/main.coffee:55:46
  at Array.forEach (native)
  at checkTreeNode (/usr/local/lib/node_modules/js-bundler/src/main.coffee:55:31)
  at /usr/local/lib/node_modules/js-bundler/src/main.coffee:53:33
  at Array.forEach (native)
  at checkTreeNode (/usr/local/lib/node_modules/js-bundler/src/main.coffee:53:18)
  at /usr/local/lib/node_modules/js-bundler/src/main.coffee:55:46
  at Array.forEach (native)
  at checkTreeNode (/usr/local/lib/node_modules/js-bundler/src/main.coffee:55:31)
  at checkCode (/usr/local/lib/node_modules/js-bundler/src/main.coffee:56:5)
  at checkTreeNode (/usr/local/lib/node_modules/js-bundler/src/main.coffee:50:17)
  at /usr/local/lib/node_modules/js-bundler/src/main.coffee:55:46
```

**Comment by zhanzhenzhen** [comment]
It's because it does not have any node module shims. If you want the "stream" module to run on browser, The only way is using browserify (that includes many shims). But if you already use some conditional statement to avoid "stream" module running on browser, you can make it dummy in the command using `-d`, or add a `module.` prefix in your code to prevent bundling it. Maybe many dummies or prefixes should be added.

**Comment by coderholic** [comment]
I wasn't hoping to use the bundle in the browser. I just wanted to combine
all of my code which is currently spread across multiple coffee files into
a single js so that it'd be easier to distribute and others to use. Are
there any bundle options that would do that for me, or is it the wrong tool
for this?

**Comment by zhanzhenzhen** [comment]
Maybe I can improve my package to support this purpose. I think it is: you don't want to publish it to npm, but only to share it with your friends, so a single file is better?

**Comment by coderholic** [comment]
Yeah that's exactly what I want to do.

**Comment by zhanzhenzhen** [comment]
Adding this feature is not difficult. We can set a router with the `require` argument removed:

``` javascript
function(exports, module) {
    module.exports = require("stream");
}
```

But overall, most likely the bundled script still won't run. Reason:
If bundling a server-specific code and you want exactly the same behavior as the unbundled version, there will be many restrictions. You can't use `require.resolve` and `module` methods except `module.exports`. If any of your code or dependendies is using them, the bundle will not work. Moreover, if any of your code or dependencies reads a non-js file (such as .json), it will not work either, because the directory context is different, and also because non-js files are not in the bundle.

So, for your case, I suggest not using bundling.
